-- Migration 0007: full taxonomy seed + company registry sync
-- Idempotent (ON CONFLICT DO NOTHING / DO UPDATE); additive only; JW untouched.

-- Add D17-D23 (additive; D1-D16 exist, must not be edited)
INSERT INTO public.faraday_domains (domain_code, domain_num, domain_name, domain_type, active)
VALUES
  ('D17', 17, 'Workforce & Labor Markets',              'core', true),
  ('D18', 18, 'Community Opposition & Regulatory Risk', 'core', true),
  ('D19', 19, 'Tax, Incentives & Fiscal Policy',        'core', true),
  ('D20', 20, 'Facility IT & Operational Technology',   'core', true),
  ('D21', 21, 'Insurance & Risk Markets',               'core', true),
  ('D22', 22, 'Industry Media & Analyst Coverage',      'core', true),
  ('D23', 23, 'Outage Intelligence & Emergency Response','core', true)
ON CONFLICT (domain_code) DO NOTHING;

-- Upsert 59 subdomains from IDF 4.0 Airtable mirror
INSERT INTO public.faraday_subdomains (subdomain_code, domain_code, display_name, theme_tags, active)
VALUES
('D1.1', 'D1', 'GPU Architecture & Roadmap', '[]'::jsonb, true),
('D1.2', 'D1', 'Rack Density & Power Density Progression', '[]'::jsonb, true),
('D1.3', 'D1', 'Competing Silicon & Alternative Accelerators', '[]'::jsonb, true),
('D2.1', 'D2', '800V DC Power Distribution', '[]'::jsonb, true),
('D2.2', 'D2', 'Behind-the-Meter Generation (BYOP/BYOG)', '[]'::jsonb, true),
('D2.3', 'D2', 'UPS, Storage & Power Conditioning', '[]'::jsonb, true),
('D2.4', 'D2', 'DC Power Delivery at the Rack', '[]'::jsonb, true),
('D3.1', 'D3', 'Interconnection Queue & Grid Access', '[]'::jsonb, true),
('D3.2', 'D3', 'State Moratorium & Legislative Landscape', '[]'::jsonb, true),
('D3.3', 'D3', 'Utility Rate Cases & PUC Proceedings', '[]'::jsonb, true),
('D4.1', 'D4', 'PE & Infrastructure Fund Activity', '[]'::jsonb, true),
('D4.2', 'D4', 'DC REIT Performance & Valuation', '[]'::jsonb, true),
('D4.3', 'D4', 'Sovereign Wealth & Institutional Capital', '[]'::jsonb, true),
('D4.4', 'D4', 'Integrated Infrastructure Vendor M&A', '[]'::jsonb, true),
('D5.1', 'D5', 'Big 5 Capex & Campus Announcements', '[]'::jsonb, true),
('D5.2', 'D5', 'Hyperscaler Custom Silicon', '[]'::jsonb, true),
('D6.1', 'D6', 'Neocloud Infrastructure', '[]'::jsonb, true),
('D6.2', 'D6', 'Sovereign AI Programs & National Compute', '[]'::jsonb, true),
('D7.1', 'D7', 'Direct-to-Chip Liquid Cooling (DLC)', '[]'::jsonb, true),
('D7.2', 'D7', 'Immersion Cooling', '[]'::jsonb, true),
('D7.3', 'D7', 'Water Use & Waterless Cooling Strategies', '[]'::jsonb, true),
('D8.1', 'D8', 'Executive Movement & C-Suite Intelligence', '[]'::jsonb, true),
('D8.2', 'D8', 'Conference Intelligence & Speaking Circuit', '[]'::jsonb, true),
('D9.1', 'D9', 'AI Factory Orchestration & DCIM', '[]'::jsonb, true),
('D9.2', 'D9', 'GPU Utilization & Compute Scheduling Economics', '[]'::jsonb, true),
('D10.1', 'D10', 'Long-Lead Equipment & Supply Chain', '[]'::jsonb, true),
('D10.2', 'D10', 'GC/EPC Capacity & Construction Execution', '[]'::jsonb, true),
('D10.3', 'D10', 'Modular & Prefabricated Data Center Delivery', '[]'::jsonb, true),
('D11.1', 'D11', 'Clean Energy Procurement (PPA/REC/CFE)', '[]'::jsonb, true),
('D11.2', 'D11', 'Carbon Accounting & Scope 1-3 Reporting', '[]'::jsonb, true),
('D14.1', 'D14', 'Site Selection Criteria & Market Scoring', '[]'::jsonb, true),
('D15.1', 'D15', 'Chip Export Controls & BIS Regime', '[]'::jsonb, true),
('D16.1', 'D16', 'Enterprise IT Cybersecurity & Cloud Security', '[]'::jsonb, true),
('D16.2', 'D16', 'OT / ICS / SCADA Cybersecurity', '[]'::jsonb, true),
('D16.3', 'D16', 'Physical Security & Access Control', '[]'::jsonb, true),
('D16.4', 'D16', 'State-Sponsored & Advanced Persistent Threats', '[]'::jsonb, true),
('D16.5', 'D16', 'Software Supply Chain & Vendor Risk', '[]'::jsonb, true),
('D16.6', 'D16', 'Security Operations & Incident Response', '[]'::jsonb, true),
('D18.1', 'D18', 'Project Opposition Register', '[]'::jsonb, true),
('D18.2', 'D18', 'Jurisdiction Posture Intelligence (JPS)', '[]'::jsonb, true),
('D19.1', 'D19', 'State & Local Tax Incentives', '[]'::jsonb, true),
('D19.2', 'D19', 'Federal Tax Policy', '[]'::jsonb, true),
('D19.3', 'D19', 'International Tax & Transfer Pricing', '[]'::jsonb, true),
('D19.4', 'D19', 'Tax Incentive Backlash & Clawback', '[]'::jsonb, true),
('D19.5', 'D19', 'Tax-Driven Deal Structuring', '[]'::jsonb, true),
('D20.1', 'D20', 'Building Management Systems & HVAC Control', '[]'::jsonb, true),
('D20.2', 'D20', 'Facility DCIM & Digital Twin', '[]'::jsonb, true),
('D21.1', 'D21', 'Data Center Property & Casualty Insurance', '[]'::jsonb, true),
('D21.2', 'D21', 'Cyber Insurance & Tech E&O', '[]'::jsonb, true),
('D21.3', 'D21', 'Climate & Parametric Risk Products', '[]'::jsonb, true),
('D21.4', 'D21', 'Lender Insurance Requirements & Risk Transfer', '[]'::jsonb, true),
('D22.1', 'D22', 'U.S. Media Coverage', '[]'::jsonb, true),
('D22.2', 'D22', 'EU Media Coverage', '[]'::jsonb, true),
('D22.3', 'D22', 'APAC / LATAM / MENA Media Coverage', '[]'::jsonb, true),
('D22.4', 'D22', 'Industry Analysts', '[]'::jsonb, true),
('D23.1', 'D23', 'Major Outage Postmortems', '[]'::jsonb, true),
('D23.2', 'D23', 'Grid Events & Physical Disasters', '[]'::jsonb, true),
('D23.3', 'D23', 'Cyber Incidents Targeting DC Infrastructure', '[]'::jsonb, true),
('D23.4', 'D23', 'Business Continuity & Disaster Recovery Practice', '[]'::jsonb, true)
ON CONFLICT (subdomain_code) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      domain_code  = EXCLUDED.domain_code,
      active       = EXCLUDED.active;

INSERT INTO public.tracking_companies (company_id, name, active) VALUES
('rec05wRsfBKkDnXEM', 'Ada Infrastructure', true),
('rec07DULsrlTrzJc4', 'AMD', true),
('rec0D3DB1M7rYWtyh', 'Amazon (AWS)', true),
('rec0EOXflB3bwqKeE', 'CoreWeave', true),
('rec0cwKqrWW8cf7rr', 'Ensono', true),
('rec0mRsWwR8T6cApN', 'Adgar', true),
('rec0uWOVvnVh6hNIl', 'Solvay', true),
('rec13W2I1DZkVFkWU', 'Nutanix', true),
('rec15UocnFUoHekAS', 'Beyond.pl', true),
('rec1hQTi4X5idTsWR', 'Bain Capital', true),
('rec1pgoED4cmw0v1f', 'Telstra InfraCo', true),
('rec1sNUjN9EvVCTzR', 'Drees & Sommer', true),
('rec1tU1Ib1qMImwO4', 'Colovore', true),
('rec22lTM5lpQa6Kpy', 'Enbridge', true),
('rec24Edd3K3S6XMjT', 'Cisco Systems', true),
('rec25eCiRVm6DJXOI', 'Goldman Sachs Alternatives', true),
('rec2B13ey4R43lH9e', 'Sumitomo Chemical', true),
('rec2JdWL0B2aHFcEy', 'Transphorm', true),
('rec2Uzp4cvTXT9zHo', 'Gaw Capital Partners', true),
('rec2YVVgqDyzmb2J5', 'Opus Interactive', true),
('rec2h3drjCYUyHWuK', 'PowerHouse Data Centers', true),
('rec34aRBRnbQR4Xtx', 'COPT', true),
('rec3VZj9mOAYb5zQO', 'Mainova WebHouse', true),
('rec3WvbV0C8dsFMSe', 'MISO', true),
('rec3dht6wqnyIQ2MO', 'Colliers', true),
('rec3fkzTY1J5UcaAs', 'Vantage Data Centers', true),
('rec3jgmUsQCgCwYbU', 'GE Vernova', true),
('rec3khvfeePVRbsOH', 'Applied Digital', true),
('rec3vF86qiNiObYHw', 'CPPIB (Canada)', true),
('rec3vHxS5XCJX1qSj', 'Kairos Power', true),
('rec3zHHuTnPu8sJ6V', 'Lenovo', true),
('rec41WR1G6vjB7lLe', '365 Data Centers', true),
('rec4IWhNnK62Fti1K', 'Baidu', true),
('rec4JYYIo0cpTDPFr', 'MTN Business', true),
('rec4PKrVSYVr1cIke', 'Aligned Data Centers', true),
('rec4ZhBTO46HHKMlE', 'NVIDIA', true),
('rec4byfULkNBIl45I', 'Dell Technologies', true),
('rec4erdy8YMbjyTMO', 'AirTrunk', true),
('rec4mN4smpyDIy1LW', 'Wiwynn', true),
('rec4rYYieXrDZOAVi', 'Ardent Data Centers', true),
('rec4vP6hXvoLunPg8', 'Flexential', true),
('rec59REQkG3QeQJcR', 'TURKCELL', true),
('rec59vEJHTa1IUqbB', 'NTT/RagingWire Data Centers', true),
('rec5CNsju0OBFVaqB', 'VoltaGrid', true),
('rec5RPQP2eU4j99oC', 'Switch', true),
('rec5XlZcot1i7vAkF', 'Daikin', true),
('rec6K9Ocv7eOGcq2t', 'CleanArc Data Centers', true),
('rec6MT3MpLXfxQ581', 'Auras Technology', true),
('rec6t3L7uxFOzqlxU', 'Bridge Data Centres (BDC)', true),
('rec6yQIHmsSNeP8R0', 'Lotte Data Communications', true),
('rec6yjHpDrXcNuI0w', 'Mapletree Industrial', true),
('rec710rH7OenTJuno', 'Nlyte Software', true),
('rec76De1LrgLBpCPr', 'AMPT', true),
('rec78et4BnHaEbkKI', 'NextEra Energy', true),
('rec7E8Bez3tp6f7VX', 'maincubes B.V.', true),
('rec7NlG3aX9mdE4Ww', 'Virtus Data Centers', true),
('rec7NvQiygG3nndEC', 'Vertiv', true),
('rec7RNde2zzWzDDtD', 'Castrol (BP)', true),
('rec7RqydrbqWZFw7x', 'Siemens', true),
('rec7avh6UxasxFoxl', 'Khazna Data Centers', true),
('rec7cGTP43LBCeWDG', 'Element Critical', true),
('rec7h9xsUh5QFdgmH', 'Actis', true),
('rec7xEF7lGICswMBb', 'ServerFarm', true),
('rec846lFBuO1rjoaA', 'Telecom Egypt', true),
('rec87gsOLkVewZXhp', 'Alibaba Cloud', true),
('rec8BboghvFPyQB2Y', 'Sabey Data Centers', true),
('rec8EwAdTG4y9HMiN', 'China Mobile International', true),
('rec8ExPGbWkaKFVkr', 'Mitsubishi Electric', true),
('rec8ItWCD3pJzw8VK', 'Infineon Technologies', true),
('rec8Zc7pul39XbfjU', 'Oppidan Investment Company', true),
('rec8xNIyt5STVh6NW', 'Nabiax', true),
('rec9HVoinzbkFYZ6U', 'Nscale', true),
('rec9KyxlIGqy2B0yI', 'Samsung Foundry', true),
('rec9S9J0FTCmeQnLG', 'Navitas Semiconductor', true),
('rec9TlxdDBpIhlUws', 'Brookfield Asset Management', true),
('rec9XhS3XiTBpQfUR', 'Engineered Fluids', true),
('rec9hpGSVbI5EnOS1', 'Galaxy Digital Inc.', true),
('rec9mwCLr3TRFfMgd', 'CBRE', true),
('rec9nYBNf87uOTArm', 'Hyperscale Data Inc', true),
('rec9ubEmS8Nee4aHP', 'Bloom Energy', true),
('rec9vOFPESPplsFTV', 'Cohesity', true),
('recA2JhS8OT9ZpS2s', 'SUNeVision', true),
('recAMNlmP41uDedPj', 'Modine Manufacturing (Airedale)', true),
('recAQP6jWd2sJeGHO', 'Racks Central', true),
('recBF0q7J8dvTmjQj', 'CyrusOne', true),
('recBHO737yPUKYFcx', 'Canon IT Solutions', true),
('recBHX1zUN6L5zyE9', 'JD Cloud & AI', true),
('recBNgk01ZPMFqX5p', 'CoreSite Realty Corporation', true),
('recBaluT8PKCeUHqm', 'iomart', true),
('recBj4tGTyzpA0Npc', 'DPR Construction', true),
('recBjiComEcRr5tIx', 'LightEdge Solutions', true),
('recBo41MaMdkUaPZE', 'Castrol', true),
('recBvBIvzbroAnhcS', 'Shell Energy', true),
('recCHkDHetNbcOCD2', 'DigitalBridge', true),
('recCMA2sHsWypv6Eg', 'JLL', true),
('recCeFfAPCTDUxlXM', 'Mortenson', true),
('recCesRYwoIuXg3kQ', 'Rittal', true),
('recCtA7njwxeY1eHN', '5C Group', true),
('recCwq2uYWVO6TkWx', 'Baidu AI Cloud', true),
('recCxIdv9w86SAWxq', 'Williams Companies', true),
('recCzst5kds7CnO6E', 'Mistral AI', true),
('recD8nD1NlzmMl1jJ', 'AIMS', true),
('recDE8tBFgXz6TYCK', 'GIC (Singapore)', true),
('recDiOggdU2iUw796', '11:11 Systems', true),
('recDlQEwhcqAJ3wPX', 'Oracle', true),
('recDr3MZTYx88QgWY', 'Chirisa Technology Parks', true),
('recDvY78AikH8nH9O', 'Anthropic', true),
('recE2d3cGyCt4Md1j', 'OVHcloud', true),
('recEEcx32bGXCO2K8', 'Broadcom', true),
('recEJHGJjb9y07lG7', 'ZutaCore', true),
('recEU3npOLM4M0Upk', 'Rackspace', true),
('recEhPKeNCDViAt8C', 'Zayo Group', true),
('recEmEwD21cz4TGPo', 'T-Systems', true),
('recEmYdchmZyc2aBB', 'Pure Storage', true),
('recEzRwy9keXdL8QU', 'du', true),
('recFFo5J1ljY3r7GV', 'Supermicro', true),
('recFHg2lq7PC816Z4', 'MYS AssetCo', true),
('recFJegXIDtnj8wb9', 'Hyperview', true),
('recFjqsQ5K9mp01Mc', 'Trane Technologies', true),
('recFtUDhhk15EjqdX', 'Nebius', true),
('recFy7RovgZzSscrL', 'DXC Technology', true),
('recG75pWjk9QdmrNI', 'YTL Data Centre Holdings', true),
('recGBt7Wh25UAto00', 'World Wide Technology (WWT)', true),
('recGKdDydbyP6SJto', 'GPX Global', true),
('recGf6DVDIPm1eSR8', 'Brookfield Asset Management', true),
('recH3Nv7YnaogIttE', 'True IDC', true),
('recH8t217bz59Qsvz', 'ADIA (Abu Dhabi Investment Authority)', true),
('recHCODIAc6nkF9uX', 'Taybo (Shanghai) Environmental Technology', true),
('recHGuzmBG3rJoXyH', 'QScale', true),
('recHJML1ZIIU159IZ', 'STMicroelectronics', true),
('recHKJ4WL199oEAhU', 'Beale Infrastructure', true),
('recHTWmnIigqfS3gm', 'Microsoft Azure', true),
('recHTjogFVMBXbj8G', 'TierPoint', true),
('recHbToafic4LclS4', 'Thesee DataCenter', true),
('recHhtlP3mGtJHQkH', 'NTT Global Data Centers', true),
('recHjDe4lFhwuQNxr', 'Holtec International', true),
('recHw6i12yTlQqY4O', 'Tract', true),
('recHwmdiOZCqgDL00', 'Atman', true),
('recI2FGNGsDkXWRqj', 'Engineered Fluids', true),
('recILlziYWU25upAC', 'Africa Data Centres', true),
('recIZJaK85xmHYAFp', 'iMasons', true),
('recIaSZD10bJKmPhB', 'xAI (Elon Musk)', true),
('recIg5TFC4I4JJe3V', 'SenseTime', true),
('recIkXpWgnwaspqKj', 'Aruba.it', true),
('recIsExLlLuNZUsyi', 'Morohub', true),
('recItKWuGHBfEdYLs', 'Schneider Electric', true),
('recJA24U3KYbVAfD7', 'ByteDance / TikTok', true),
('recJGPLhy39eumZYH', 'TeraWulf Inc', true),
('recJQhPTEZ3H3nK5D', 'Menlo Equities', true),
('recJeIUTrmXstV8C8', 'Apple', true),
('recJj8qaMQxdVuY7g', 'Submer', true),
('recJmUoS3CuH6KvR0', 'Nano-Join', true),
('recJuCcoAKgmh7J4K', 'Asterion Industrial Partners', true),
('recJvROimbzH26J0R', 'QTS Realty', true),
('recK7TfemMFuXwcWE', 'NYISO', true),
('recKAQNyUlFWGNTBd', 'WEKA', true),
('recKEwoluNwXeCJyF', 'Chemours', true),
('recKScAzzfuYKnHUT', 'Talen Energy / Susquehanna Nuclear', true),
('recKhKHpzFz5PyVBm', 'Chunghwa Post', true),
('recKjyuBmOgHkAoLS', 'Resonac Holdings', true),
('recKmWmJvNs0vSwPN', 'Digital Realty Bersama', true),
('recKtUJYU9wufOmBq', 'GIGABYTE Technology', true),
('recKuD6WlFZgwELMU', 'Raxio Group', true),
('recKx8SuJ1OzG2j1G', 'Blackstone', true),
('recL18U0hqyGZH9I1', 'PAIX Data Centres', true),
('recLAM3I6O3mIm3A6', 'BlackChamber Group', true),
('recLLsm4T6Vlshk81', 'Luxconnect', true),
('recLTnmNseJo2CwL2', 'Galaxy Data Centers', true),
('recLTqVMovBlzsC5B', 'Green Revolution Cooling (GRC)', true),
('recLXDgogCUCxhM23', 'Cologix', true),
('recLhmtMEu2IXGrI3', 'AIMS', true),
('recM1pyM96p85uZZ2', 'Green Revolution Cooling (GRC)', true),
('recM6wXF7XZeQmJtp', 'Equinix', true),
('recM9Cwyrx2zfGplZ', 'Wolfspeed', true),
('recMBbrKXlWOuO1Ik', 'Hitachi Vantara', true),
('recMU27e1iS4po77j', 'Chunghwa Telecom', true),
('recMfIK0nWVXPEPM0', 'Entergy', true),
('recMlZwynhV0TgHre', 'Converge ICT Solutions', true),
('recNAnliA1CSOwATE', 'iM Critical', true),
('recNMzGPeQrO4vaQc', 'Google / Alphabet', true),
('recNZFvVijMFUyatZ', 'Triara', true),
('recNkcRd2WLSG8PLr', 'First Solar', true),
('recNncJYZVJapR4wR', 'OpCore', true),
('recO9072i5K5iTHz0', 'Radiant (Brookfield)', true),
('recOEuAAy9g9NSWI3', 'Hammond Power Solutions', true),
('recOFD9zZBQxekWaV', 'Telstra', true),
('recOjPDKEqR9HkTAZ', 'DataBank', true),
('recOkN3GgRSmxavOQ', 'Etisalat by e&', true),
('recOuhAHCjdKXtY1q', 'Intersect Power', true),
('recP0smGTQrt0QoRG', 'Gaw Capital Partners', true),
('recPL0lphcwBye78M', 'Kao Data', true),
('recPT6kK36RpUDA4s', 'AEP Ohio', true),
('recPcGheg5Hx9O24j', 'DG Matrix', true),
('recPomYMqWL62csgm', 'evroc', true),
('recQ0IdcLqAs5qpod', 'EcoDataCenter', true),
('recQ5ZDHFCGGToA2L', 'Lambda Labs', true),
('recQ6Z5iy5j48BPIT', 'Intel', true),
('recQ9XfqEfJ40Z29V', 'BW Digital', true),
('recQCHcGhPwgFzQtZ', 'Submer', true),
('recQFEpZiI4R1wsLN', 'Neurok Thermocon Inc', true),
('recQM5XVp5Rzw9jVf', 'CAISO', true),
('recQViYq3fCKzNftD', 'Airtel Nxtra', true),
('recQZ1T0bG3I3Nhf7', 'Rain AI', true),
('recQZdg1zVmWG8jFN', 'Heliox', true),
('recQqT0KDCFQOcgSW', 'Blue Owl / Beale Infrastructure', true),
('recQrVRAsWF3vHxlZ', 'Novva', true),
('recR6f2htfCuuh44I', 'SK Telecom (SKT)', true),
('recRBSOOy6GvWkdsL', 'Constellation Energy', true),
('recRMUESXAjef0POz', 'Temasek', true),
('recRYdzWDrWh3zdxW', 'Lefdal Mine Datacenter', true),
('recRfBYHh9edCXcob', 'GE Vernova', true),
('recRuFSCrcIX1bAG9', 'G42 Cloud', true),
('recRvEor13VUTF1Ov', 'Chunghwa Telecom', true),
('recS5adNulGai2wQa', 'run:ai (NVIDIA)', true),
('recS6kAPc46SStl1a', 'Ares Management / Ada Infrastructure', true),
('recSDZlx3q6fxRgPj', 'Yahoo! Japan', true),
('recSEtoabXG239HBf', 'Saudi Data & AI Authority (SDAIA)', true),
('recSIagy7EXbL3NZ3', 'Motivair (by Schneider Electric)', true),
('recSeAeoeS5SrekHO', 'PJM Interconnection', true),
('recSzJRTWGnb30QY2', 'TPG', true),
('recT4XflnwV9um2mX', 'Stargate (OpenAI/SoftBank/Oracle)', true),
('recTBzeJtmUc42TGW', 'EkkoSense', true),
('recTMs0CnvsZCXjbF', 'Eaton', true),
('recTXjDzgtTXvRU7p', 'JetCool', true),
('recTiI42vP8epsJ9O', 'Hewlett Packard Enterprise (HPE)', true),
('recTqSdCl6B8tdqX4', 'Crusoe', true),
('recU1vMJ8fluOtZyc', 'Rowan Digital Infrastructure', true),
('recU3hbeyHkbZG0Jg', 'HUMAIN (Saudi Arabia)', true),
('recUAXD5k9fmZaUX1', 'CAISO', true),
('recUNSzOTOFEWL0Al', 'AECOM', true),
('recUU03TC6NipdQ0H', '3M', true),
('recUUUJHRNUqE6DyM', 'Iron Mountain', true),
('recUccdKxyeCWowDp', 'CENTRA (Data Centers)', true),
('recUpVUI1uPoSKI7I', 'CISA', true),
('recUrle3Momx25wXJ', 'Entergy', true),
('recVBCEsBGSDK52tc', 'OpenAI', true),
('recVQOyg6Y1STzTtJ', 'Data Foundry', true),
('recVXQ1VVNBOgTXei', 'Spark', true),
('recVdZVkVwPDtSNOi', 'Global Technical Realty', true),
('recVulR3pJdLYw19d', 'VoltaGrid', true),
('recWP77iAscO1lt4j', 'IDC Frontier', true),
('recWR8TR1IxcICCM0', 'LiSAT', true),
('recWdcFtPPNBNNoc0', 'DDN (DataDirect Networks)', true),
('recWh05S0ZHhFxPi5', 'T5 Data Centers', true),
('recWlfDSUMRXNwpEF', 'China Mobile International', true),
('recWuaDXTTPaljScA', 'Talen Energy', true),
('recX0QsCC2Gn9QUot', 'DataBank', true),
('recXYPWAmqW7D7fJY', 'Northern Data', true),
('recXliwSAtRZBtGC8', 'EDC/Edged', true),
('recY47xW3zbG0NuoS', 'Digital Realty Trust', true),
('recYFHVUSHIymlgrO', 'Crypt-ON (Singapore / SEA)', true),
('recYI2jZxJikccL2Z', 'FPT Telecom', true),
('recYSPh2hIND5Hvzw', 'Digital Parks Africa', true),
('recYpElNCu3ZJf8xZ', 'QTS Realty Trust', true),
('recYq5MUyiRgBWriu', 'Tavily (Nebius)', true),
('recYs4iFiEzevjvqh', 'Coherent Corp', true),
('recZ8X7PPOW3LMeIe', 'Digital Realty / PlatformDIGITAL', true),
('recZ8axf9nnVmBg6F', 'Colliers', true),
('recZCvw69zlMYsnop', 'SK Holdings C&C', true),
('recZKXoKMbdnONMPy', 'Varentec', true),
('recZOBzjMs4Y1iYkx', 'Atos', true),
('recZheiWmbahCDHus', 'Google DeepMind', true),
('recZqkXjXMBrVhP5c', 'Telus', true),
('recZz4wV1VEvPFBQH', 'Parker Lord', true),
('reca3LCIgbN7eq2P1', 'H5 Data Centers', true),
('reca4SYanvfUFWn8W', 'Schneider Electric IT (UK/EMEA)', true),
('recaIR8zUSEepyfsk', 'Baidu AI Cloud', true),
('recaRKQ0OuiAYLZHp', 'DC Blox', true),
('recaTTFMmKO3s5hOs', 'Wingu.Africa', true),
('recaVVwfUayWcnfhK', 'Turner Construction', true),
('recaemb64z9mhkESc', 'KKR', true),
('recarnxggM9ozdXUP', 'Open Access Data Centres', true),
('recbBLhyNJOtAxDQF', 'Soluna', true),
('recbUOq6BqLTHuoaa', 'Meta', true),
('recbVG7IyktATc2Of', 'Stackinfrastructure', true),
('recbdAGfnjGEVH41Y', 'Tyson (cooling)', true),
('recbkwyX8Au6YlW0Q', 'Bechtel Nuclear', true),
('recboveSIeuRi6RYf', 'MDXi (MainOne)', true),
('recbwo5h1uFAOhRfj', 'Arista Networks', true),
('recc0SwcEp0Pd4hhe', 'Crusoe Energy', true),
('recc6PNY48DFrvNEz', 'Dominion Energy', true),
('reccF09vVcWHLJetN', 'Noovle', true),
('reccQyB3iCfDhu9GN', 'BroadBand Tower', true),
('reccTbR8tu4YfuEiF', 'Virtual Power Systems', true),
('reccbBKVuLQR4utSd', 'SoftBank Group', true),
('reccfniQTtpsFKdTM', 'DELSKA', true),
('reccmCKuseXKSWibb', 'LiquidStack', true),
('reccpBCR94rwCmJQJ', 'Accenture', true),
('reccwUwKnWuaUJnAr', 'Sentinum', true),
('recd6vfOqjx4qZ6xn', 'Start Campus', true),
('recdEeYexBzimGu3o', 'NTT / RagingWire Data Centers', true),
('recdVtBIxm5uvJIFE', 'Pulsant', true),
('recdW65ZMy8FztyZI', 'Inspur', true),
('recdXj8G9JIRIB9UP', 'ERMCO', true),
('recdYrWuyJE5IBcWf', 'DE-CIX', true),
('recdgqbVwlZTXY6eq', 'Noris Network', true),
('recdkoetivxaecAVp', 'Henkel', true),
('recdqpJkX87K1jsTd', 'First Colo', true),
('recdsKo8buI454HDP', 'Marsh', true),
('receKx4kBjp48EtCL', 'Olkaria EcoCloud Data Center', true),
('receM1tHyecErMib9', 'Stellium Datacenters', true),
('receWuCunBNNb1jXm', 'Reliance Communications', true),
('recel34V38dPterbG', 'EdgeConneX', true),
('recerwhA3Xg4wj3B6', '21st Century Technologies', true),
('recf4DkKyDgLvGcdC', 'CISA', true),
('recfIlvfrxBXjA8bn', 'Evoque Data Center Solutions', true),
('recfRacvV1NmrECaU', 'Ascendas REIT', true),
('recfcUkdRQ5A2uNWF', 'Claro', true),
('recfowzHOVsYQCV1G', 'TSMC', true),
('recfsA5SBHUC9McKR', 'Juniper Networks (HPE)', true),
('recg70FeKzaF4m0uY', 'Hitachi Energy', true),
('recgC5SdLBsA3ESu9', 'OneAs1a', true),
('recgU6U0CUxHSNyeA', 'Iceotope', true),
('recglNCyPqvjJGVny', 'PIF (Saudi Public Investment Fund)', true),
('recgrFTqaNSIrYlbm', 'ERCOT', true),
('recgt4Bj75a13NUBk', 'Aligned Energy', true),
('rechJKYo8JEk1EteU', 'PhoenixNAP', true),
('rechQWDXzqefvqllf', 'Duke Energy', true),
('rechSKDEEZdNMtBWx', 'Tencent Cloud', true),
('rechWgqYNq9HxIRdF', 'Carrier Global', true),
('rechq9N4aVM75kLlA', 'Efficient Power Conversion (EPC)', true),
('rechqOwaLq3y1CFzn', 'Enovum Data Centers', true),
('rechrOSPVoIt0ny7p', 'Powell Industries', true),
('reci9CPcc9voc5c1y', 'Asperitas', true),
('reciGWQr07140zWTt', 'Calyos', true),
('reciIlZaqgXsCWgjs', 'NeoFan', true),
('reciOSP3fj5wAaddj', 'Starwood Capital', true),
('reciSL3A1YLcgubcX', 'Claro', true),
('reciXR3gcUzRBH2Vt', 'Telehouse Canada', true),
('reciisF7qsmh3wH5z', 'VAST Data', true),
('recj8lql4VSJdZGsX', 'Mistral AI', true),
('recj9pF8lzR1qokFU', 'Vodafone', true),
('recjAsjTp63TkzbD3', 'TierPoint', true),
('recjB8SLXc89Jo9wu', 'MISO', true),
('recjLp4Lllafo1rKJ', 'MGX (Abu Dhabi)', true),
('recjMziMPovpXKY2P', 'DPR Construction', true),
('recje6v5Fi09OQFlO', 'Quantum Switch', true),
('recjgJosFKIrevr9H', 'Prime Data Centers', true),
('recjgwTl2GFaUfj2B', 'GE Vernova', true),
('recjiJhLoxGoCk4nM', 'NextEra Energy', true),
('recjl83EXeR0v6A9x', 'Expedient', true),
('recjlpFsPXKsTJx25', 'Chunghwa Telecom', true),
('recjwYHfJ7Uz7kXHl', 'Sabey Data Centers', true),
('reck1u7IQVTiFWpRF', 'EdgeCore Internet Real Estate', true),
('reckAHfuI5N86oDJ0', 'IDC Frontier', true),
('reckBDiohxPTxRyTb', '365 Data Centers', true),
('reckJFzHgTDypAkid', 'Prime Data Centers', true),
('reckLFMvn6UbjQiqc', 'Wingu.Africa', true),
('reckQpDjS2rT2OMeL', 'Data Foundry', true),
('reckT9V2GYXDvCui3', 'GE Vernova', true),
('reckXJ8j3COvB9SLH', 'Portus Data Centers', true),
('reckarIKhcCyB0W6X', 'Uptime Institute', true),
('reckkX6p9hoCcdIzr', 'Telehouse Canada', true),
('recknBsFVKFj5R9EO', 'du', true),
('recko2VibYuo2IA8W', 'Oklo Inc', true),
('reclN8UsPnta2kMjE', 'Aramco Digital', true),
('reclNmWpvy8w4Qiv6', 'Beyond.pl', true),
('reclUBkjVh4m9V4Lv', 'Crane Data Centers', true),
('reclhBuoblI6KFC7V', 'Noovle', true),
('recliAaQnWEDv6kzQ', 'Henkel', true),
('recm0b7v1eplRkLex', 'Datacenter United', true),
('recm8UmYR8LexYZ2Q', 'Iron Mountain Data Centers', true),
('recmKFNJa30paOXut', 'HUMAIN / stc center3 JV', true),
('recmM5tACoLJJMiO5', 'PowerHouse Data Centers', true),
('recmUyevijXcyX5Iz', 'EdgeConneX', true),
('recmgSGN74yvUtQnf', 'TerraPower', true),
('recmr1QTTf98VniV7', 'Hyperscale Data Inc', true),
('recmsEGBtyrNH27Mf', 'Inspur', true),
('recmu3N2eoVIKopB1', 'Racks Central', true),
('recn04gC9YIyAvHTl', 'Taybo (Shanghai) Environmental Technology', true),
('recn8uQ5oBdDWKXOU', 'Elisa', true),
('recnBIp2xsl9bit8p', 'Motivair Corporation', true),
('recnVwsaJJWZBD5Rv', 'Gaw Capital Partners', true),
('recneDRHqzSLqDqpL', 'Lenovo', true),
('recnnWT7liS9uPyiD', 'OneAs1a', true),
('recnodZLOJEABYz0F', 'DEEP (Data Center)', true),
('recnpbRHEEL9qJhUq', 'NetApp', true),
('reco84cc7dOQnxhtM', 'KKR', true),
('recoA5RVzYQK6SpqF', 'SK Telecom (SKT)', true),
('recoAieFuV9m718sW', 'Bloom Energy', true),
('recoFIxR3NfoQ6CYd', 'CAISO', true),
('recoNWSyBxxY606Cy', 'Zayo Group', true),
('recobo78hkgGKbfJK', 'Baidu AI Cloud', true),
('recogBvrU88XixiHR', 'Optage', true),
('recohYxxYqJAUro4I', 'IDC Frontier', true),
('recokbFoId0yG52wF', 'Rack Centre', true),
('recoommvMmWlhQC6g', 'Data Foundry', true),
('recotgU8gvEylDpD4', 'PhoenixNAP', true),
('recpI3IjJvXiFO7gq', 'Bloom Energy', true),
('recplKpV3plnkiKm1', 'Iron Mountain Data Centers', true),
('recppdFbdFvQ6NQOD', 'Macquarie Data Centres', true),
('recpzE4JP06aFepa4', 'GleSYS', true),
('recq1Fm2Rpo0Kst5X', 'LiquidCool Solutions', true),
('recq8pWwUGwo7hQmm', 'Macquarie Asset Management', true),
('recqD4FA2kU2XYysZ', 'IXAfrica', true),
('recqHssjoIi0jBHAV', 'LiquidCool Solutions', true),
('recqM0CwyQbTLAm3k', 'Groq', true),
('recqOfLI9FEtNooXX', 'Luxconnect', true),
('recqPF2v0Jm3XM9yr', 'Redapt', true),
('recqYW8GIgDfmShUE', 'Henkel', true),
('recqbyZ4dGhjmLGy4', 'X-energy', true),
('recqgRWrW6qUfoHVM', 'TeraWulf Inc', true),
('recqpJTmhQVs1upr8', 'Claro', true),
('recqxkGO64pME7Qfl', 'Arieca', true),
('recrVM7dlz5OslsOk', 'HKCOLO', true),
('recrZL5HruewSv03F', 'Expedient', true),
('recroHkVRkWK3jrzt', 'Vodafone', true),
('recru7GcuRZWTaTWG', 'Datacenter United', true),
('recs20ASEAxYaHYS8', 'Solvay', true),
('recs45SwaKGvhbZuO', 'DG Matrix', true),
('recsJ54zzokqoyuWb', 'Groq', true),
('recsNLdY6m2yMDmfC', 'AIMS', true),
('recsjBLUFQ1VILety', 'Cadence Design Systems', true),
('recslhgwcLjn0QO9F', 'Datacenter United', true),
('recsq6yNDVuQjv3PS', 'China Mobile International', true),
('recswVnYatcsl7N2K', 'EdgeConneX', true),
('rect0EKtJXiLwHcZD', 'Siemens', true),
('rect1UIHH8DUpK5Fv', 'EdgeCore Internet Real Estate', true),
('rectDOHEXaF5RF8JP', 'AMD', true),
('rectDuqsyOcdScfU3', 'DataBank', true),
('rectQLh7BAbCAU100', 'evroc', true),
('rectjrGQ6NyBY0p8U', 'AI Infrastructure Partnership (AIP)', true),
('rectqQekvyaxyhYrK', 'SmartD Technologies', true),
('recuDMJATIJVJB1Xr', 'Uptime Institute', true),
('recuEq1G5IPkPvUCp', 'Cologix', true),
('recuQkafW47Usfo2r', 'Entergy', true),
('recubOS91Qw39qQwr', 'Open Access Data Centres', true),
('recugvKjgrGht8PVi', 'Arieca', true),
('recupo0HATGhFmwHC', 'Cologix', true),
('recv36AWPuQU8SCiN', 'CISA', true),
('recvEztlxrFNQS6ob', 'Vigilent', true),
('recvHppRtbbApgki2', 'Gabia', true),
('recvKSHKjXb97jm9y', 'ABB', true),
('recvM2durxA0Lit8p', 'Quantum Switch', true),
('recvQBNUKhXKi5pAK', 'Groq', true),
('recvzmziMHKeME9LZ', 'Redapt', true),
('recvznI9FgHymFH7A', 'Soluna', true),
('recw1ccI0DjAuK1Ts', 'Nlyte Software', true),
('recwM0JDN17sXNMtm', 'JD Cloud & AI', true),
('recwV3WdYAWkrhk6h', 'Expedient', true),
('recwVl7EbskPNeVm3', 'onsemi', true),
('recwefLpmEWGM7w4N', 'Starwood Capital', true),
('recwfrResH0QUGqCA', 'Ampere Computing', true),
('recwp5WLRY050Ntje', 'Hyperscale Data Inc', true),
('recwqtNBBXoZA99FV', 'Macquarie Asset Management', true),
('recwtBeGAvZpfXh3E', 'Cibicom', true),
('recx4rmfnTGOZtJGq', 'Inspur', true),
('recxEWIQZVHaqJh8e', 'Colliers', true),
('recxFCVAFTWBUjt6F', 'EdgeCore Internet Real Estate', true),
('recxOtV33tLJCigr9', 'Kao Data', true),
('recxb4XkQsP46vWsr', 'LiSAT', true),
('recxwLkiZNQwTYaqB', 'DPR Construction', true),
('recy1uaHmZRpGKeqw', 'Accelsius', true),
('recy3Irfz1RHeqjS2', 'Tyson (cooling)', true),
('recyBF8bu4PoufnEp', 'Leuk Teleport & Data Centre', true),
('recyOZqyTKhPXdQ5w', 'Arieca', true),
('recyPmBqPRHBccyPx', 'Macquarie Data Centres', true),
('recyTN60EPWGJvWJN', '365 Data Centers', true),
('recya4uhHLMjDZXNm', 'PowerHouse Data Centers', true),
('recyod2qqtCJU2iDD', 'Chunghwa Post', true),
('recyqggTsBPOojCZJ', 'Dawiyat', true),
('recyvQbB90Qxjq53A', 'Customized Energy Solutions', true),
('recz0XZQkNFa5Osrj', 'Brookfield Asset Management', true),
('recz7YGsOmPd4RoWv', 'Submer', true),
('recz84sDdBKbKIDN2', 'Grid Strategies LLC', true),
('reczBeh0tsCL2SPra', 'Beyond.pl', true),
('reczb3XshXWL3MFGV', 'AMD', true),
('reczcQEPmwpfgTa8z', 'Daou Technology', true),
('reczj88ZNJSgN8cqZ', 'Temasek', true)
ON CONFLICT (company_id) DO UPDATE SET name = EXCLUDED.name, active = EXCLUDED.active;
